## More info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
[build]
  command = "yarn build"

  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[context.production.plugins]]
  package = "@netlify/plugin-lighthouse"

  [context.production.plugins.inputs]
  output_path = "reports/lighthouse.html"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "base-uri 'none'; connect-src 'self' *.netlify.app; default-src 'none'; font-src 'self'; form-action 'none'; frame-ancestors 'none'; frame-src 'self' *.netlify.com; img-src 'self' *.netlify.app; require-trusted-types-for 'script'; script-src 'self' *.netlify.app; style-src 'self' 'unsafe-inline';"
    Referrer-Policy = "same-origin"
    Strict-Transport-Security = "max-age=63072000; includeSubdomains; preload"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"