## More info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
[build]
  command = "yarn build"

  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
  output_path = "reports/lighthouse.html"