## More info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
[build]
  command = "yarn build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
    output_path = "reports/lighthouse.html"

[[context.branch-deploy.plugins]]
  package = "@netlify/plugin-lighthouse"

  [context.branch-deploy.plugins.inputs]
  output_path = "reports/lighthouse.html"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "camera=(), microphone=()"
    Referrer-Policy = "same-origin"
    Strict-Transport-Security = "max-age=63072000; includeSubdomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"