name: Build
on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set-up Node
        uses: actions/setup-node@v2

      - name: Check-out Code
        uses: actions/checkout@v2

      - name: Prepare
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Snyk
        run: yarn test:snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
